monitor/chart/controllers.py
# Import flask dependencies
from flask import Blueprint, request, render_template, \
                  flash, g, session, redirect, url_for,\
                  send_from_directory
from flask.ext.login import login_required
from monitor import db,app
from monitor.item.models import Area,Service,Host,Aws,Itemtype,Item,Itemdatatype
from monitor.zabbix.models import Zabbixhosts
from monitor.chart.models import *
from monitor.MonitorException import *
from monitor.chart.search import *
from monitor.chart.displaychart import *
from monitor.chart.generate import *
from monitor.chart.overall import *

from flask.ext.principal import Permission, RoleNeed
admin_permission = Permission(RoleNeed('1')).union(Permission(RoleNeed('0')))

from config import WINDOW_CHART,CHART_INIT_DEFAULT_MESSAGE, IN_LOCAL


import json,time

mod_chart = Blueprint('chart', __name__, url_prefix='/chart')

@mod_chart.route('/')
@login_required
def mainboard():
    return render_template("chart/main.html")

@mod_chart.route('/window/', methods=['GET', 'POST'])
@login_required
def window():
	
	windows = g.user.windows.filter_by(type=WINDOW_CHART).all()
	services = Service.query.all()
	itemtypes = Itemtype.query.all()
	tmp_arr = []
	aws_tmp_arr = []
	for it in itemtypes:
		if it.aws == None:
			tmp_arr.append(it.itemtypename)
		else:
			item = it.items.first()
			aws_tmp_arr.append(item.itemname)
	itemtypenames = json.dumps(tmp_arr)
	aws_itemtypenames = json.dumps(aws_tmp_arr)
	return render_template("chart/window.html",title='Window',services=services,windows=windows,itemtypenames=itemtypenames,aws_itemtypenames=aws_itemtypenames)


@mod_chart.route('/page/', methods=['GET', 'POST'])
@login_required
def page():
	services = Service.query.all()
	pages = g.user.pages.all()
	windows = g.user.windows.filter_by(type=WINDOW_CHART).all()
	itemtypes = Itemtype.query.all()
	tmp_arr = []
	aws_tmp_arr = []
	for it in itemtypes:
		if it.aws == None:
			tmp_arr.append(it.itemtypename)
		else:
			item = it.items.first()
			aws_tmp_arr.append(item.itemname)
	itemtypenames = json.dumps(tmp_arr)
	aws_itemtypenames = json.dumps(aws_tmp_arr)
	return render_template("chart/page.html",title='Page',services=services,pages=pages,windows=windows,itemtypenames=itemtypenames,aws_itemtypenames=aws_itemtypenames)


@mod_chart.route('/report')
@login_required
def report():
	u = g.user
	emailschedule = u.schedules.all()
	report = u.reports.all()
	return render_template('chart/reportmain.html',title='Report',emailschedule=emailschedule,report=report)

@mod_chart.route('/addreport/', methods=['GET', 'POST'])
@login_required
def addreport():
	services = Service.query.all()

	itemtypes = Itemtype.query.all()
	tmp_arr = []
	aws_tmp_arr = []
	for it in itemtypes:
		if it.aws == None:
			tmp_arr.append(it.itemtypename)
		else:
			item = it.items.first()
			aws_tmp_arr.append(item.itemname)
	itemtypenames = json.dumps(tmp_arr)
	aws_itemtypenames = json.dumps(aws_tmp_arr)

	if request.method == 'POST':
		try:
			reportname = request.form['reportname']
			selectedmetrics = json.loads(request.form['selectedmetrics'])
			scaletype = request.form['scaletype']
			functiontype = request.form['functiontype']
			title = request.form['title']
			description = request.form['description']
			owner = g.user

			save_result = generate_report.save_report(reportname,selectedmetrics,scaletype,functiontype,owner,title,description)
			app.logger.info(g.user.username + ' add a report ' + reportname )
			db.session.commit()
		except Exception, e:
			db.session.rollback()
			flash(str(e),'danger')
			return redirect(url_for('chart.addreport'))
		else:
			flash('you add a report','success')
			return redirect(url_for('chart.report'))
		finally:
			db.session.remove()

	return render_template('chart/report.html',title='report',services=services,itemtypenames=itemtypenames,aws_itemtypenames=aws_itemtypenames)

@mod_chart.route('/report/delete/<reportid>', methods=['GET', 'POST'])
@login_required
def reportdelete(reportid):
	try:
		# r = Report.query..get(reportid)
		generate_report.delete_report(reportid)
		app.logger.info(g.user.username + ' delete a report ' + reportid )

		# db.session.delete(r)
		db.session.commit()
	except Exception, e:
		db.session.rollback()
		flash(str(e),'danger')
	else:
		flash(' you delete a report ','success')
	finally:
		db.session.remove()

	return redirect(url_for('chart.report'))

@mod_chart.route('/reportlist/', methods=['GET', 'POST'])
@login_required
def reportlist():
	user = g.user
	reports = user.reports
	result = []
	for r in reports:
		tmp = {}
		tmp['reportname'] = r.reportname
		tmp['reportid'] = r.reportid
		result.append(tmp)
	return json.dumps(result)

@mod_chart.route('/addschedule/', methods=['GET', 'POST'])
@login_required
def addschedule():
	if request.method == 'POST':
		try:
			f = request.form
			email = []
			for key in f.keys():
			    for value in f.getlist(key):
			    	if len(value) != 0:
						if key == 'email[]':
							email.append(value)
			reportids = json.loads(request.form['reportid'])
			subject = request.form['emailsubject']
			u = g.user
			period = request.form['period']
			start_time = request.form['timestart']
			timezone = request.form['timezone']
		
			es = generate_schedule.save_schedule(subject,reportids,email,period,start_time,u,timezone)
			db.session.commit()
			generate_schedule.add_specific_cron(es)
			all_es = Emailschedule.query.all()
			generate_schedule.update_schedule_data_2_s3(all_es)
			app.logger.info(g.user.username + ' save an email schedule ' )
		except Exception, e:
			db.session.rollback()
			flash(str(e),'danger')
		else:
			flash('Save email schedule successfully','success')
			return redirect(url_for('chart.report'))
		finally:
			db.session.remove()
		
		
	return render_template('chart/schedule.html',title='schedule')

@mod_chart.route('/schedule/delete/<emailscheduleid>', methods=['GET'])
@login_required
def scheduledelete(emailscheduleid):
	try:
		es = Emailschedule.query.get(emailscheduleid)
		generate_schedule.delete_schedule(es)
		db.session.commit()
		generate_schedule.delete_specific_cron(es)
		generate_schedule.update_schedule_data_2_s3()
		app.logger.info(g.user.username + ' delete an email schedule ' )
	except Exception, e:
		db.session.rollback()
		flash(str(e),'danger')
	else:
		flash('you delete a schedule','success')
	finally:
		db.session.remove()

	return redirect(url_for('chart.report'))


@mod_chart.route('/init/', methods=['GET', 'POST'])
@login_required
def init():
	result = {}
	info = None
	init_result_bool = False
	init_result = None
	if request.method == 'POST':
		try:
			request_data = json.loads(request.data)
			selected_metrics = request_data['selected_metrics']
			chart_config = request_data['chart_config']

			item_list = Chart.smr_2_itemlist(selected_metrics)
			for itemid in item_list:
				item = Item.query.get(itemid)
				if item != None and item.itemtype.aws != None and not admin_permission.can():
					raise Exception('Some lines in your chart is not authorized to access')

			init_result = Chart.init(selected_metrics,chart_config)
			init_result_bool = True
			info = Chart.info
			Chart.info = CHART_INIT_DEFAULT_MESSAGE
			result['selected_metrics'] = selected_metrics
			result['chart_config'] = chart_config
		except Exception, e:
			import traceback,sys
			traceback.print_exc(file=sys.stdout)

			print str(e)
			info = str(e)

	result['init_result_bool'] = init_result_bool
	result['init_result'] = init_result
	result['info'] = info


	return json.dumps(result)

@mod_chart.route('/update/', methods=['GET', 'POST'])
@login_required
def update():
	result = {}
	info = None
	update_result_bool = False
	update_result = None
	if request.method == 'POST':
		# try:
		request_data = json.loads(request.data)
		selected_metrics = request_data['selected_metrics']
		chart_config = request_data['chart_config']
		update_result = Chart.update(selected_metrics,chart_config)
		update_result_bool = True
		info = 'success'
	
	result['update_result_bool'] = update_result_bool
	result['update_result'] = update_result
	result['info'] = info
	return json.dumps(result)



@mod_chart.route('/save/window', methods=['GET', 'POST'])
@login_required
def save_window():
	result = {}
	info = None
	save_result_bool = False
	save_result = None
	if request.method == 'POST':
		try:
			request_data = json.loads(request.data)
			selected_metrics = request_data['selected_metrics']
			chart_config = request_data['chart_config']
			windowname = request_data['windowname']
			user = g.user
			window = Chart.save_window_chart(selected_metrics,chart_config,windowname,user)

			db.session.commit()
			app.logger.info(g.user.username + ' save a window chart : ' +  windowname)

			save_result = {'name':windowname,'indexId':window.windowid}

			save_result_bool = True

			info = 'success'
		except Exception, e:
			import sys, traceback
			traceback.print_exc(file=sys.stdout)
			db.session.rollback()
			print str(e)
			info = str(e)

	result['save_result_bool'] = save_result_bool
	result['save_result'] = save_result
	result['info'] = info
	return json.dumps(result)

@mod_chart.route('/load/window', methods=['GET', 'POST'])
@login_required
def load_window():

	result = {}
	info = None
	load_result_bool = False
	load_result = None
	index = None
	selected_windowname = None

	if request.method == 'GET':
		try:
			windowid = request.args.get('windowid',None)
			index = request.args.get('render_index',None)
			selected_windowname = request.args.get('selected_windowname',None)
			load_result = Chart.load_window_chart(windowid)
			info = 'success'
			load_result_bool = True
		except Exception, e:

monitor/odata/controllers.py
import json
from flask import Blueprint, request, render_template, flash, g, \
        redirect, url_for

from flask.ext.principal import RoleNeed, UserNeed, Permission
from flask.ext.login import login_required

admin_permission = Permission(RoleNeed('1')).union(Permission(RoleNeed('0')))

mod_odata = Blueprint('odata', __name__, url_prefix='/odata', template_folder \
    = 'templates')

from monitor.odata.models import *
from monitor.functions import gen_operational_itemtype, str_2_clock


@mod_odata.route('/')
@login_required
def odata_main():
    
    return render_template('odata/main.html', title='Operational Data')

@mod_odata.route('/mechine')
@login_required
def mechine_main():
    oit = gen_operational_itemtype()
    monthes = odmonth.get_all_timestr()
    return render_template('odata/mechine_main.html', title='Operational Data', \
        oit=oit, monthes=monthes)

@mod_odata.route('/monthdata', methods=['POST', 'GET'])
@login_required
def monthdata():
    result = {}
    load_result_bool = False
    load_result = {}
    info = None
    try:
        month = request.args.get('month',None)
        # time = 'March 2015'
        if month is None:
            raise Exception('Invalid args, month cannot be None')

        clock = str_2_clock(month, '%B %Y')

        odm = odmonth.query.filter_by(beginclock=clock).first()
        load_result['data'] = []
        if odm is not None:
            load_result['data'] = odm.gen_table_content()

        load_result['month'] = month
        info = 'success'
        load_result_bool = True

    except Exception, e:
        info = str(e)
        print info
        load_result = {}
        load_result_bool = False

    result['load_result'] = load_result
    result['load_result_bool'] = load_result_bool
    result['info'] = info

    return json.dumps(result)


@mod_odata.route('/userdevice')
@login_required
def userdevice_main():
    region_data = {}
    for r in region.query.all():
        region_data[r.regionshort] = r.regionlong

    month_data = count.get_all_month_str()


    return render_template('odata/userdevice_main.html', \
        title='Operational Data', region_data=region_data, month_data=month_data)

@mod_odata.route('/r_m_uddata', methods=['POST', 'GET'])
@login_required
def region_month_userdevice_data():
    result = {}
    load_result_bool = False
    load_result = {}
    info = None
    try:
        month = request.form.get("month", None)
        regionshort = request.form.get("region", None)
        # time = 'March 2015'
        if month is None or regionshort is None:
            raise Exception('Invalid args, month or region cannot be None')

        clock = str_2_clock(month, '%B %Y')
        r = region.query.filter_by(regionshort=regionshort).first()
        if r is None:
            raise Exception(' region input does not exist')
        

        rc_result = {}
        region_counts = r.counts.filter('clock >=' + str(clock)).all()
        for rc in region_counts:
            if rc.clock not in rc_result:
                rc_result[rc.clock] = {}

            rc_result[rc.clock][rc.counttype.counttypename] = rc.value
        


        load_result['data'] = rc_result
        info = 'success'
        load_result_bool = True

    except Exception, e:
        info = str(e)
        print info
        load_result = {}
        load_result_bool = False

    result['load_result'] = load_result
    result['load_result_bool'] = load_result_bool
    result['info'] = info

    return json.dumps(result)
            

monitor/templates/dashboard.html
{% extends "layout.html" %}
{% block body %}
<!-- <h2>dashboard</h2> -->
<!-- <a href = '{{url_for("auth.config")}}'>auth</a> -->
<!-- <a href = '{{url_for("chart.mainboard")}}'>chart</a> -->
<!-- <a href = '{{url_for("item.mainboard")}}'>item</a> -->

<div class="container marketing">
	<div class="row">
		<div class="col-lg-4">
			<img class="img-circle" src="{{ url_for('static',filename='img/user.png')}}" alt="Generic placeholder image" style="width:140px; height:140px">
			<h2>User Configuration</h2>
			<p>During this part you can add,delete or change an user' fields of different kind of roles.Different role has different authority</p>
			<p><a class="btn btn-default" href="{{url_for('auth.config')}}" role="button">View details</a></p>
		</div>
		<div class="col-lg-4">
			<img class="img-circle" src="{{ url_for('static',filename='img/chart.png')}}" alt="Generic placeholder image" style="width:140px; height:140px">
			<h2>Chart</h2>
			<p>Checkout two kinds of catogaries of displaying monitoring data which is fetched by zabbix or sended via interface.</p>
			<p><a class="btn btn-default" href="{{url_for('chart.mainboard')}}" role="button">View details</a></p>
		</div>
		<div class="col-lg-4">
			<img class="img-circle" src="{{ url_for('static',filename='img/item.png')}}" alt="Generic placeholder image" style="width:140px; height:140px">
			<h2>Item</h2>
			<p>It is all about item configuration.You can either make changes for monitoring host or monitoring items</p>
			<p><a class="btn btn-default" href="{{url_for('item.mainboard')}}" role="button">View details</a></p>
		</div>
	</div>
</div>
{% endblock %}

monitor/templates/email.html
<div class="form-group">
        <label class="col-sm-3 control-label">Email Address</label>
        <div class="col-sm-5">
            <input type="text" class="form-control" name="email[]" placeholder="Receiver email address"/>
        </div>
        <div class="col-sm-4">
            <button type="button" class="btn btn-default addButton"><i class="fa fa-plus"></i></button>
        </div>
    </div>

    <!-- The option field template containing an option field and a Remove button -->
    <div class="form-group hide" id="optionTemplate">
        <div class="col-sm-offset-3 col-sm-5">
            <input class="form-control" type="text" name="email[]" placeholder="Receiver email address"/>
        </div>
        <div class="col-sm-4">
            <button type="button" class="btn btn-default removeButton"><i class="fa fa-minus"></i></button>
        </div>
    </div>

monitor/templates/flash.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}

<!-- <ul class=flashes> -->
    <!-- {% for category, message in messages %} -->
      <!-- <li class="{{ category }}">{{ message }}</li> -->
    <!-- {% endfor %} -->
<!-- </ul> -->

{% for category,message in messages %}
<div class="alert alert-{{category}}">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}

monitor/templates/layout.html
<!doctype html>
<html>
<head>
    {% if title %}
    <title>{{ title }} - Monitor</title>
    {% else %}
    <title>Monitor</title>
    {% endif %}
    <link href="{{url_for('static',filename='css/style.css')}}" rel="stylesheet"></link>
    <link href="{{url_for('static',filename='css/bootstrap.min.css')}}" rel="stylesheet" media="screen"></link>
    <link href="{{url_for('static',filename='css/bootstrap-theme.min.css')}}" rel="stylesheet" ></link>
    <link href="{{url_for('static',filename='css/carousel.css')}}" rel="stylesheet" ></link>
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/bootstrapValidator.css')}}"></link>

    <script type="text/javascript" src="{{url_for('static',filename='js/jquery-2.1.1.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static',filename='js/bootstrap.min.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static',filename='js/bootstrapValidator.js')}}"></script>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    
</head>
<body>

<div class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{{ url_for('index') }}">Monitor</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{url_for('chart.mainboard')}}">Chart </a></li>
                    {% if g.user.is_admin() %}
                    <li><a href="{{url_for('billing.billing_main')}}">Billing </a></li>
                    <li><a href="{{url_for('odata.odata_main')}}">Daily </a></li>
                    <li><a href="{{url_for('item.mainboard')}}">Metrics </a></li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if g.user.is_authenticated() %}
                    <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                    {% else %}
                    <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
</div>



<div class='container'>
    <div class="jumbotron">
	
    {% include 'flash.html' %}
	{% block body %}{% endblock %}
</div>
</div>
</body>	
</html>

monitor/templates/saving.html
<div class="modal fade bs-example-modal-sm" tabindex="-1" id="forsaving" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
        <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Waiting</h4>
              </div>
              <div class="modal-body">
                waiting ...
              </div>
        </div>
    </div>
  </div>
</div>

monitor/templates/testpost.html
{% extends 'layout.html' %}
{% block body %}
<script type="text/javascript">
	$(function()
	{
		$(".post").click(function()
		{
			arr = {};
			arr1 = [];
			arr1.push(1);
			arr1.push(2);
			arr1.push(3);
			arr2 = "1234";
			arr['1'] = arr1;
			arr['2'] = arr2;

			var option = {  
               url: '/chart/post/',  
               type: 'POST',  
               data: JSON.stringify({'arr':arr}),  
               dataType: 'json', 
               contentType : 'application/json', 
               success: function (result) { console.log(result); }  
           	};  
			$.ajax(option); 
		});
	});
</script>

<button class="post">Post</button>
{% endblock %}