monitor/billing/controllers.py
import json, sys, traceback
from flask import Blueprint, request, render_template, flash, g, session, \
        redirect, url_for

from flask.ext.principal import RoleNeed, UserNeed, Permission
from flask.ext.login import login_required

mod_billing = Blueprint('billing', __name__, url_prefix='/billing')

admin_permission = Permission(RoleNeed('1')).union(Permission(RoleNeed('0')))

from monitor.billing.models import *
from monitor.functions import str_2_clock, opentime_from_month_csv

@mod_billing.route('/')
@login_required
@admin_permission.require(http_exception=403)
def billing_main():
    time_str_arr = billingtime.get_all_timestr()
    return render_template('billing/billsreport.html', title='billing', \
        time_arr=time_str_arr)


@mod_billing.route('/billsreport', methods=['POST', 'GET'])
@login_required
@admin_permission.require(http_exception=403)
def billsreport():
    result = {}
    info = None
    load_result_bool = False
    load_result = {}
    try:
        time = request.args.get('time',None)
        # time = 'March 2015'
        if time is None:
            raise Exception('Invalid args, time cannot be None')

        clock = str_2_clock(time, '%B %Y')
        consolidated_bill_data = {}
        for s in awsservice.query.all():
            tmps_r = s.build_list(clock)
            if len(tmps_r['region_info']) > 0:
                consolidated_bill_data[s.productname] = tmps_r


        linkedaccount_data = {}
        for l in linkedaccount.query.all():
            if l.fee_of_time(clock) is None:
                continue
            linkedaccount_data[l.linkedaccountname] = l.fee_of_time(clock)

        summary_data = {}
        summary_data['Total'] = 0
        summary_data['payers'] = {}
        for p in payeraccount.query.all():
            if p.fee_of_time(clock) is None:
                continue
            summary_data['Total'] += p.fee_of_time(clock)
            summary_data['payers'][p.payeraccountid] = {}
            summary_data['payers'][p.payeraccountid]['Total'] = \
                p.fee_of_time(clock)
            summary_data['payers'][p.payeraccountid]['InvoiceDate'] = \
                p.billingrows.filter_by(billingperiodstartdate=clock)\
                    .first().invoicedate

        region_data = {}
        region_data['Total'] = 0
        region_data['regions'] = {}
        for az in availablezone.query.all():
            tmp_fee = az.fee_of_time(clock)
            if tmp_fee is None:
                continue
            region_data['Total'] += tmp_fee
            region_data['regions'][az.regionname] = {}
            region_data['regions'][az.regionname]['Total'] = tmp_fee
            region_data['regions'][az.regionname]['lc'] = {}
            for l in linkedaccount.query.all():
                if az.fee_of_time(clock, l) is not None:
                    region_data['regions'][az.regionname]['lc']\
                    [l.linkedaccountname] = az.fee_of_time(clock, l)

        load_result['time'] = time
        load_result['consolidated_bill_data'] = consolidated_bill_data
        load_result['linkedaccount_data'] = linkedaccount_data
        load_result['summary_data'] = summary_data
        load_result['region_data'] = region_data
        info = 'success'
        load_result_bool = True
    except Exception, e:
        traceback.print_exc(file=sys.stdout)
        info = str(e)

    result['info'] = info
    result['load_result_bool'] = load_result_bool
    result['load_result'] = load_result

    return json.dumps(result)


@mod_billing.route('/billsreport/la', methods=['POST', 'GET'])
@login_required
@admin_permission.require(http_exception=403)
def ladata():
    result = {}
    info = None
    load_result_bool = False
    load_result = {}
    try:
        time = request.args.get('time', None)
        linkedaccountname = request.args.get('laname', None)
        load_collapse_id = request.args.get('render_selector_id', None)
        # time = 'March 2015'
        if time is None or linkedaccountname is None:
            raise Exception('Invalid args')

        l = linkedaccount.query.filter_by(linkedaccountname=linkedaccountname).first()
        if l is None:
            raise Exception('Linked account do not exist with name:' + linkedaccountname)

        clock = str_2_clock(time, '%B %Y')

        load_result['data'] = l.build_list(clock)

        load_result['time'] = time
        load_result['laname'] = linkedaccountname
        load_result['load_collapse_id'] = load_collapse_id
        info = 'success'
        load_result_bool = True

    except Exception, e:
        info = str(e)
        load_result_bool = False
        load_result = None

    result['info'] = info
    result['load_result_bool'] = load_result_bool
    result['load_result'] = load_result

    return json.dumps(result)

monitor/chart/controllers.py
# Import flask dependencies
from flask import Blueprint, request, render_template, \
                  flash, g, session, redirect, url_for,\
                  send_from_directory
from flask.ext.login import login_required
from monitor import db,app
from monitor.item.models import Area,Service,Host,Aws,Itemtype,Item,Itemdatatype
from monitor.zabbix.models import Zabbixhosts
from monitor.chart.models import *
from monitor.MonitorException import *
from monitor.chart.search import *
from monitor.chart.displaychart import *
from monitor.chart.generate import *
from monitor.chart.overall import *

from flask.ext.principal import Permission, RoleNeed
admin_permission = Permission(RoleNeed('1')).union(Permission(RoleNeed('0')))

from config import WINDOW_CHART,CHART_INIT_DEFAULT_MESSAGE, IN_LOCAL


import json,time

mod_chart = Blueprint('chart', __name__, url_prefix='/chart')

@mod_chart.route('/')
@login_required
def mainboard():
    return render_template("chart/main.html")

@mod_chart.route('/window/', methods=['GET', 'POST'])
@login_required
def window():
	
	windows = g.user.windows.filter_by(type=WINDOW_CHART).all()
	services = Service.query.all()
	itemtypes = Itemtype.query.all()
	tmp_arr = []
	aws_tmp_arr = []
	for it in itemtypes:
		if it.aws == None:
			tmp_arr.append(it.itemtypename)
		else:
			item = it.items.first()
			aws_tmp_arr.append(item.itemname)
	itemtypenames = json.dumps(tmp_arr)
	aws_itemtypenames = json.dumps(aws_tmp_arr)
	return render_template("chart/window.html",title='Window',services=services,windows=windows,itemtypenames=itemtypenames,aws_itemtypenames=aws_itemtypenames)


@mod_chart.route('/page/', methods=['GET', 'POST'])
@login_required
def page():
	services = Service.query.all()
	pages = g.user.pages.all()
	windows = g.user.windows.filter_by(type=WINDOW_CHART).all()
	itemtypes = Itemtype.query.all()
	tmp_arr = []
	aws_tmp_arr = []
	for it in itemtypes:
		if it.aws == None:
			tmp_arr.append(it.itemtypename)
		else:
			item = it.items.first()
			aws_tmp_arr.append(item.itemname)
	itemtypenames = json.dumps(tmp_arr)
	aws_itemtypenames = json.dumps(aws_tmp_arr)
	return render_template("chart/page.html",title='Page',services=services,pages=pages,windows=windows,itemtypenames=itemtypenames,aws_itemtypenames=aws_itemtypenames)


@mod_chart.route('/report')
@login_required
def report():
	u = g.user
	emailschedule = u.schedules.all()
	report = u.reports.all()
	return render_template('chart/reportmain.html',title='Report',emailschedule=emailschedule,report=report)

@mod_chart.route('/addreport/', methods=['GET', 'POST'])
@login_required
def addreport():
	services = Service.query.all()

	itemtypes = Itemtype.query.all()
	tmp_arr = []
	aws_tmp_arr = []
	for it in itemtypes:
		if it.aws == None:
			tmp_arr.append(it.itemtypename)
		else:
			item = it.items.first()
			aws_tmp_arr.append(item.itemname)
	itemtypenames = json.dumps(tmp_arr)
	aws_itemtypenames = json.dumps(aws_tmp_arr)

	if request.method == 'POST':
		try:
			reportname = request.form['reportname']
			selectedmetrics = json.loads(request.form['selectedmetrics'])
			scaletype = request.form['scaletype']
			functiontype = request.form['functiontype']
			title = request.form['title']
			description = request.form['description']
			owner = g.user

			save_result = generate_report.save_report(reportname,selectedmetrics,scaletype,functiontype,owner,title,description)
			app.logger.info(g.user.username + ' add a report ' + reportname )
			db.session.commit()
		except Exception, e:
			db.session.rollback()
			flash(str(e),'danger')
			return redirect(url_for('chart.addreport'))
		else:
			flash('you add a report','success')
			return redirect(url_for('chart.report'))
		finally:
			db.session.remove()

	return render_template('chart/report.html',title='report',services=services,itemtypenames=itemtypenames,aws_itemtypenames=aws_itemtypenames)

@mod_chart.route('/report/delete/<reportid>', methods=['GET', 'POST'])
@login_required
def reportdelete(reportid):
	try:
		# r = Report.query..get(reportid)
		generate_report.delete_report(reportid)
		app.logger.info(g.user.username + ' delete a report ' + reportid )

		# db.session.delete(r)
		db.session.commit()
	except Exception, e:
		db.session.rollback()
		flash(str(e),'danger')
	else:
		flash(' you delete a report ','success')
	finally:
		db.session.remove()

	return redirect(url_for('chart.report'))

@mod_chart.route('/reportlist/', methods=['GET', 'POST'])
@login_required
def reportlist():
	user = g.user
	reports = user.reports
	result = []
	for r in reports:
		tmp = {}
		tmp['reportname'] = r.reportname
		tmp['reportid'] = r.reportid
		result.append(tmp)
	return json.dumps(result)

@mod_chart.route('/addschedule/', methods=['GET', 'POST'])
@login_required
def addschedule():
	if request.method == 'POST':
		try:
			f = request.form
			email = []
			for key in f.keys():
			    for value in f.getlist(key):
			    	if len(value) != 0:
						if key == 'email[]':
							email.append(value)
			reportids = json.loads(request.form['reportid'])
			subject = request.form['emailsubject']
			u = g.user
			period = request.form['period']
			start_time = request.form['timestart']
			timezone = request.form['timezone']
		
			es = generate_schedule.save_schedule(subject,reportids,email,period,start_time,u,timezone)
			db.session.commit()
			generate_schedule.add_specific_cron(es)
			all_es = Emailschedule.query.all()
			generate_schedule.update_schedule_data_2_s3(all_es)
			app.logger.info(g.user.username + ' save an email schedule ' )
		except Exception, e:
			db.session.rollback()
			flash(str(e),'danger')
		else:
			flash('Save email schedule successfully','success')
			return redirect(url_for('chart.report'))
		finally:
			db.session.remove()
		
		
	return render_template('chart/schedule.html',title='schedule')

@mod_chart.route('/schedule/delete/<emailscheduleid>', methods=['GET'])
@login_required
def scheduledelete(emailscheduleid):
	try:
		es = Emailschedule.query.get(emailscheduleid)
		generate_schedule.delete_schedule(es)
		db.session.commit()
		generate_schedule.delete_specific_cron(es)
		generate_schedule.update_schedule_data_2_s3()
		app.logger.info(g.user.username + ' delete an email schedule ' )
	except Exception, e:
		db.session.rollback()
		flash(str(e),'danger')
	else:
		flash('you delete a schedule','success')
	finally:
		db.session.remove()

	return redirect(url_for('chart.report'))


@mod_chart.route('/init/', methods=['GET', 'POST'])
@login_required
def init():
	result = {}
	info = None
	init_result_bool = False
	init_result = None
	if request.method == 'POST':
		try:
			request_data = json.loads(request.data)
			selected_metrics = request_data['selected_metrics']
			chart_config = request_data['chart_config']

			item_list = Chart.smr_2_itemlist(selected_metrics)
			for itemid in item_list:
				item = Item.query.get(itemid)
				if item != None and item.itemtype.aws != None and not admin_permission.can():
					raise Exception('Some lines in your chart is not authorized to access')

			init_result = Chart.init(selected_metrics,chart_config)
			init_result_bool = True
			info = Chart.info
			Chart.info = CHART_INIT_DEFAULT_MESSAGE
			result['selected_metrics'] = selected_metrics
			result['chart_config'] = chart_config
		except Exception, e:
			import traceback,sys
			traceback.print_exc(file=sys.stdout)

			print str(e)
			info = str(e)

	result['init_result_bool'] = init_result_bool
	result['init_result'] = init_result
	result['info'] = info


	return json.dumps(result)

@mod_chart.route('/update/', methods=['GET', 'POST'])
@login_required
def update():
	result = {}
	info = None
	update_result_bool = False
	update_result = None
	if request.method == 'POST':
		# try:
		request_data = json.loads(request.data)
		selected_metrics = request_data['selected_metrics']
		chart_config = request_data['chart_config']
		update_result = Chart.update(selected_metrics,chart_config)
		update_result_bool = True
		info = 'success'
	
	result['update_result_bool'] = update_result_bool
	result['update_result'] = update_result
	result['info'] = info
	return json.dumps(result)



@mod_chart.route('/save/window', methods=['GET', 'POST'])
@login_required
def save_window():
	result = {}
	info = None
	save_result_bool = False
	save_result = None
	if request.method == 'POST':
		try:
			request_data = json.loads(request.data)
			selected_metrics = request_data['selected_metrics']
			chart_config = request_data['chart_config']
			windowname = request_data['windowname']
			user = g.user
			window = Chart.save_window_chart(selected_metrics,chart_config,windowname,user)

			db.session.commit()
			app.logger.info(g.user.username + ' save a window chart : ' +  windowname)

			save_result = {'name':windowname,'indexId':window.windowid}

			save_result_bool = True

			info = 'success'
		except Exception, e:
			import sys, traceback
			traceback.print_exc(file=sys.stdout)
			db.session.rollback()
			print str(e)
			info = str(e)

	result['save_result_bool'] = save_result_bool
	result['save_result'] = save_result
	result['info'] = info
	return json.dumps(result)

@mod_chart.route('/load/window', methods=['GET', 'POST'])
@login_required
def load_window():

	result = {}
	info = None
	load_result_bool = False
	load_result = None
	index = None
	selected_windowname = None

	if request.method == 'GET':
		try:
			windowid = request.args.get('windowid',None)
			index = request.args.get('render_index',None)
			selected_windowname = request.args.get('selected_windowname',None)
			load_result = Chart.load_window_chart(windowid)
			info = 'success'
			load_result_bool = True
		except Exception, e:

monitor/templates/chart/information.html
<!DOCTYPE html>
<html>
<body>



{% for attach in attach_info %}
	<p>[ {{attach.title}} ] </p>
	<img src="cid:{{ attach.cid }}">
	<p>[ {{attach.discription}} ] </p>
{% endfor %}

</body>
</html>

monitor/templates/chart/main.html
{% extends "layout.html" %}
{% block body %}
<div class="container marketing">
	<div class="row">
		<div class="col-lg-4">
			<img class="img-circle" src="{{ url_for('static',filename='img/singlechart.png')}}" alt="Generic placeholder image" style="width:140px; height:140px">
			<h2>Single Chart</h2>
			<p>Can dynamically add monitoring series into the chart.</p>
			<p><a class="btn btn-default" href="{{url_for('chart.window')}}" role="button">View details</a></p>
		</div>
		<div class="col-lg-4">
			<img class="img-circle" src="{{ url_for('static',filename='img/ninecharts.png')}}" alt="Generic placeholder image" style="width:140px; height:140px">
			<h2>Multiple Charts</h2>
			<p>Can add at most nine charts into a table of displaying monitoring data</p>
			<p><a class="btn btn-default" href="{{url_for('chart.newpage')}}" role="button">View details</a></p>
		</div>
		<div class="col-lg-4">
			<img class="img-circle" src="{{ url_for('static',filename='img/overall.jpg')}}" alt="Generic placeholder image" style="width:140px; height:140px">
			<h2>Overall</h2>
			<p>Overall of healthy data and business data in all monitored servers.</p>
			<p><a class="btn btn-default" href="{{url_for('chart.overall')}}" role="button">View details</a></p>
		</div>
	</div>
</div>
{% endblock %}

monitor/templates/chart/pagetable.html
{% for i in range(0,9) %}
	{% if i % 3 == 0%}
		<div class='row' >
	{% endif %}
	<div class='col-lg-4 page text-center' sortId='{{i}}'>
		<div class="panel panel-default" style="margin-bottom:0px;">
			<div class="panel-heading clearfix chartpanel" style="padding: 1px 15px;"><b>tmp chart {{i}}</b>
				<div class="btn-group pull-right">
					<button class="btn btn-default setting">
						<span class="glyphicon glyphicon-cog"></span>
					</button>
					<button class="btn btn-default remove">
						<span class="glyphicon glyphicon-remove-circle"></span>
					</button>
				</div>
			</div>
		</div>
		
		<div container='col-lg-4 page' class='chartinpage' sortId='{{i}}'>
			<div class="row">
				<button class='btn btn-info btn-lg load_sc' sortId='{{i}}'>Import Single Chart Saved</button>
				<button class='btn btn-primary btn-lg page' sortId='{{i}}'>New Generate</button>
			</div>
		</div>
	</div>
	{% if i % 3 == 2%}
		</div>
	{% endif %}
{% endfor %}

monitor/templates/chart/reportlist.html
<div class="IndexDiv" type='report'></div>

monitor/templates/chart/reportmain.html
{% extends "layout.html" %}
{% block body %}

<script type="text/javascript">
$(document).ready(function(){
    $("#myTab a").click(function(e){
        e.preventDefault();
        $(this).tab('show');
    });
    $('a[delete=1]').click(function()
    {
    	info = $(this).attr("info");
    	if (confirm('You want to delete ' + info)) {
    		 
    		href = $(this).attr('path');
    		window.location.href=href;
    	}
    });
});
</script>

<ul class="nav nav-tabs" id="myTab">
  <li role="presentation" class="active"><a href="#schedule">Email Schedule</a></li>
  <li role="presentation"><a href="#report">Reports</a></li>
</ul>

<div class="tab-content">
	<div id="schedule" class="tab-pane fade in active">
		<div class="panel panel-default">

		  	<table class="table table-striped">
					<thead>
						<th>#</th>
						<th>subject</th>
						<th>frequency</th>
						<th>start time</th>
						<th>time zone</th>
						<th>reports</th>
						<th>receivers</th>
						<th>delete</th>
					</thead>
					<tbody>
						{% for s in emailschedule %}
						<tr>
							<td>{{s.emailscheduleid}}</td>
							<td>{{s.subject}}</td>
							<td>{{s.frequency}}</td>
							<td>{{s.starttime}}</td>
							<td>{{s.timezone}}</td>
							<td>{{s.reports.all()}}</td>
							<td>{{s.receivers.all()}}</td>
							<td><a href="#" path="/chart/schedule/delete/{{s.emailscheduleid}}" deletetype="emailschedule" delete="1" info="Schedule:{{s.subject}}" >delete</a></td>
						</tr>
						{% endfor %}
					</tbody>
			</table>
		</div>
	</div>
	<div id="report" class="tab-pane fade">
		<div class="panel panel-default">
		  	<table class="table table-striped">
					<thead>
						<th>#</th>
						<th>Report Name</th>
						<th>Scale Type</th>
						<th>Function Type</th>
						<th>Title</th>
						<th>Description</th>
						<th>Delete</th>
					</thead>
					<tbody>
						{% for r in report %}
						<tr>
							<td>{{r.reportid}}</td>
							<td>{{r.reportname}}</td>
							<td>{{r.scaletype}}</td>
							<td>{{r.functiontype}}</td>
							<td>{{r.title}}</td>
							<td>{{r.discription}}</td>
							<td><a href="#" path="/chart/report/delete/{{r.reportid}}" deletetype="report" delete="1" info="Report:{{r.reportname}}">delete</a></td>
						</tr>
						{% endfor %}
					</tbody>
			</table>
		</div>
	</div>
</div>


	



	<a href='{{url_for("chart.addschedule")}}'> Add Schedule</a>
	<a href='{{url_for("chart.addreport")}}'> Add Report</a>
{% endblock %}

monitor/templates/chart/test.html
<!doctype html>
<html>
<head>

<script type="text/javascript" src="{{url_for('static',filename='js/jquery-2.1.1.js')}}"></script>

</head>
<body>



<script type="text/javascript">
$(document).ready(function()
{
	function Parenizor(value) {
	    this.setValue(value);
	}
	 
	Parenizor.method('setValue', function (value) {
	    this.value = value;
	    return this;
	});
	 
	Parenizor.method('getValue', function () {
	    return this.value;
	});
	 
	Parenizor.method('toString', function () {
	    return '(' + this.getValue() + ')';
	});

	myParenizor = new Parenizor(0);
	myString = myParenizor.toString();
});
</script>

<span id="account-title" class="content-title-font account-ctrl" style="cursor: pointer;" href="">Already have a account?</span>

</body>
</html>

monitor/templates/chart/window.html
<!doctype html>
<html>
<head>
    {% if title %}
    <title>{{ title }} - Monitor</title>
    {% else %}
    <title>Monitor</title>
    {% endif %}
    <link href="{{url_for('static',filename='css/style.css')}}" rel="stylesheet"></link>
    <link href="{{url_for('static',filename='css/bootstrap.min.css')}}" rel="stylesheet" media="screen"></link>
    <link href="{{url_for('static',filename='css/bootstrap-theme.min.css')}}" rel="stylesheet" ></link>
    <link href="{{url_for('static',filename='css/carousel.css')}}" rel="stylesheet" ></link>
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/bootstrapValidator.css')}}"></link>
    <script type="text/javascript" src="{{url_for('static',filename='js/jquery-2.1.1.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static',filename='js/bootstrap.min.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static',filename='js/bootstrapValidator.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static',filename='js/highstock.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static',filename='js/chart.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static',filename='js/window_base.js')}}"></script>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    
</head>

<script type="text/javascript">
$(document).ready(function()
{

    var itemtypetags = {{ itemtypenames|safe }};
    var aws_itemtypetags = {{ aws_itemtypenames|safe }};
    // console.log(aws_itemtypetags);
    // console.log(itemtypetags);

    set_auto_complete_in_dashboard();
    set_auto_complete_in_main();
    set_auto_complete_in_billing();

    function set_auto_complete_in_dashboard()
    {
        // var new_arr = $.merge( itemtypetags, aws_itemtypetags);
        var db_search_input_selector = "input.dashboard-search";
        $(db_search_input_selector).autocomplete({
            source: itemtypetags
        });
    }

    function set_auto_complete_in_main()
    {
        var main_search_input_selector = "input.main-search";
        $(main_search_input_selector).autocomplete({
            source: itemtypetags
        });
    }

    function set_auto_complete_in_billing()
    {
        var billing_search_input_selector = 'input.billing-search';
        $(billing_search_input_selector).autocomplete({
            source: aws_itemtypetags
        });
    }

    var f = new window_base($(window).height() - $('div.navbar-fixed-top').height() - 20);

    // f.set_main_height($(window).height() - $('div.navbar-fixed-top').height() - 20);
    
    $(window).resize(function(e)
    {
        if (e.target == window)
        {
            f.resize_caller($(window).height() - $('div.navbar-fixed-top').height() - 20);
        }
    });

    // $(window).load(function()
    // {
    //     f.window_load_set();
    // });


});
</script>


<body class="window-base-body" style="padding-bottom:0px">


<div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{{ url_for('index') }}">Monitor</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{url_for('chart.mainboard')}}">Chart </a></li>
                    {% if g.user.is_admin() %}
                    <li><a href="{{url_for('billing.billing_main')}}">Billing </a></li>
                    <li><a href="{{url_for('auth.config')}}">Auth </a></li>
                    <li><a href="{{url_for('item.mainboard')}}">Item </a></li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if g.user.is_authenticated() %}
                    <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                    {% else %}
                    <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
</div>
        



    {% include 'chart/window_base.html' %}



</body> 
</html>

monitor/templates/chart/window_base.html
<link type="text/css" href="{{url_for('static',filename='css/window_base.css')}}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/bootstrap-glyphicons.css')}}">
<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/bootstrap-datetimepicker.css')}}">
<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/jquery-ui.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/dataTables.bootstrap.css')}}">
<script type="text/javascript" src="{{url_for('static',filename='js/moment.js')}}"></script>
<script type="text/javascript" src="{{url_for('static',filename='js/jquery.dataTables.min.js')}}"></script>
<script type="text/javascript" src="{{url_for('static',filename='js/dataTables.bootstrap.js')}}"></script>


<script type="text/javascript" src="{{url_for('static',filename='js/bootstrap-datetimepicker.js')}}"></script>
<script type="text/javascript" src="{{url_for('static',filename='js/jquery-ui.min.js')}}"></script>




<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="sidebar-page active"><a href="javascript:;" page="dashboard" class="sidebar-page">Dashboard <span class="sr-only">(current)</span></a></li>
            <li class="sidebar-page"><a href="javascript:;" page="billing" class="sidebar-page">Billing</a></li>
            <li class="sidebar-page">
            	<a href="javascript:;" page="metric" class="sidebar-page">Metric</a>
            	<ul>
                    <li class="selected-metrics"><a href="javascript:;" class="sidebar-option" locate="main-sidebar">Selected Metrics</a></li>
                    <li><a href="javascript:;" option="Basic Metrics" class="sidebar-option" locate="main-sidebar">Basic Metrics</a></li>
                    {% for s in services %}
                        <li><a href="javascript:;" option="{{s.servicename}}" class="sidebar-option" locate="main-sidebar">{{s.servicename}}</a></li>
            		{% endfor %}
            	</ul>
            </li>
            <li class="sidebar-page">
                <a href="javascript:;" class="sidebar-load">History Chart Saved</a>
                <ul class="sidebar-load-ul">
                    {% for w in windows %}
                        <li>
                            <a href="javascript:;" class="chart-saved-li" indexId="{{w.windowid}}" name="{{w.windowname}}">{{w.windowname}}
                                <span class="glyphicon glyphicon-remove remove" aria-hidden="true" indexId="{{w.windowid}}"></span>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </li>
            <li class="sidebar-page">
                <a href="javascript:;" class="sidebar-save">Click Save Button to Save</a>
                <div class="navbar-form">
                    <input type="text" class="form-control save-name" placeholder="input saved name">
                    <button class="btn btn-default form-control save">Save</button>
                </div>
            </li>
          </ul>
          
          
        </div>

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            
            
            
            {% include 'chart/window_main.html' %}

            
        </div>
      </div>
</div>