monitor/odata/models.py
from monitor import db
from monitor.functions import clock_2_str

MONTH_FORMAT = '%B %Y'
DATE_FORMAT = '%Y/%m/%d'


class intervaldata(db.Model):
    """docstring for intervaldata"""

    intervaldataid = db.Column(db.Integer, primary_key=True)
    timefrom = db.Column(db.BigInteger, nullable=False)
    timeto = db.Column(db.BigInteger, nullable=False)
    groupname = db.Column(db.String(128), nullable=False)
    itemkey = db.Column(db.String(128), nullable=False)
    displayname = db.Column(db.String(128))
    sumv = db.Column(db.Float)
    odmonth_id = db.Column(db.Integer, db.ForeignKey("odmonth.odmonthid"))

    def __init__(self, timefrom, timeto, groupname, itemkey, displayname,\
         sumv, odmonth):
        self.timefrom = timefrom
        self.timeto = timeto
        self.groupname = groupname
        self.itemkey = itemkey
        self.displayname = displayname
        self.sumv = sumv
        self.odmonth = odmonth

class odmonth(db.Model):
    """docstring for odmonth"""
    odmonthid = db.Column(db.Integer, primary_key=True)
    beginclock = db.Column(db.Integer, unique=True)
    intervaldatas = db.relationship("intervaldata", backref="odmonth", \
        lazy="dynamic")

    def __init__(self, beginclock):

        self.beginclock = beginclock

    @classmethod
    def get_all_timestr(cls):
        result = []
        for bt in cls.query.order_by(cls.beginclock.desc())\
            .all():
            clock = bt.beginclock
            time_str = clock_2_str(clock, MONTH_FORMAT)
            if time_str is not None:
                result.append(time_str)

        return result

    def gen_table_content(self):
        result = {}
        index_date_map = []
        index = 0
        for itvd in self.intervaldatas.order_by(intervaldata.timefrom).all():
            date = clock_2_str(itvd.timefrom, DATE_FORMAT)
            if not result.has_key(date):
                result[date] = {}
                index_date_map.append(date)

            result[date][itvd.displayname] = itvd.sumv

        order_result = []
        for di in xrange(len(index_date_map)):
            tmp = {
                "date" : index_date_map[di],
                "data" : result[index_date_map[di]]
            }
            order_result.append(tmp)
        return order_result

class region(db.Model):
    """docstring for region"""
    regionid = db.Column(db.Integer, primary_key=True)
    regionshort = db.Column(db.String(128), nullable=False)
    regionlong = db.Column(db.String(128), nullable=False)
    counts = db.relationship("count", backref="region", \
        lazy="dynamic")
    def __init__(self, regionshort, regionlong):
        self.regionshort = regionshort
        self.regionlong = regionlong


class counttype(db.Model):
    """docstring for counttype """
    counttypeid = db.Column(db.Integer, primary_key=True)
    counttypename = db.Column(db.String(128), nullable=False)
    counts = db.relationship("count", backref="counttype", \
        lazy="dynamic")
    def __init__(self, counttypename):
        self.counttypename = counttypename

class count(db.Model):
    """docstring for count"""
    countid = db.Column(db.Integer, primary_key=True)
    value = db.Column(db.Integer, nullable=False)
    clock = db.Column(db.BigInteger, nullable=False)
    region_id = db.Column(db.Integer, db.ForeignKey("region.regionid"))
    counttype_id = db.Column(db.Integer, db.ForeignKey("counttype.counttypeid"))

    def __init__(self, value, clock, region, counttype):
        self.value = value
        self.clock = clock
        self.region = region
        self.counttype = counttype

    @classmethod
    def get_all_month_str(cls):
        result = []
        for c in cls.query.order_by(count.clock).all():
            month_str = clock_2_str(int(c.clock), MONTH_FORMAT)
            if month_str not in result:
                result.append(month_str)
        return result




        

        
            
        

monitor/odata/controllers.py
import json
from flask import Blueprint, request, render_template, flash, g, \
        redirect, url_for

from flask.ext.principal import RoleNeed, UserNeed, Permission
from flask.ext.login import login_required

admin_permission = Permission(RoleNeed('1')).union(Permission(RoleNeed('0')))

mod_odata = Blueprint('odata', __name__, url_prefix='/odata', template_folder \
    = 'templates')

from monitor.odata.models import *
from monitor.functions import gen_operational_itemtype, str_2_clock


@mod_odata.route('/')
@login_required
def odata_main():
    
    return render_template('odata/main.html', title='Operational Data')

@mod_odata.route('/mechine')
@login_required
def mechine_main():
    oit = gen_operational_itemtype()
    monthes = odmonth.get_all_timestr()
    return render_template('odata/mechine_main.html', title='Operational Data', \
        oit=oit, monthes=monthes)

@mod_odata.route('/monthdata', methods=['POST', 'GET'])
@login_required
def monthdata():
    result = {}
    load_result_bool = False
    load_result = {}
    info = None
    try:
        month = request.args.get('month',None)
        # time = 'March 2015'
        if month is None:
            raise Exception('Invalid args, month cannot be None')

        clock = str_2_clock(month, '%B %Y')

        odm = odmonth.query.filter_by(beginclock=clock).first()
        load_result['data'] = []
        if odm is not None:
            load_result['data'] = odm.gen_table_content()

        load_result['month'] = month
        info = 'success'
        load_result_bool = True

    except Exception, e:
        info = str(e)
        print info
        load_result = {}
        load_result_bool = False

    result['load_result'] = load_result
    result['load_result_bool'] = load_result_bool
    result['info'] = info

    return json.dumps(result)


@mod_odata.route('/userdevice')
@login_required
def userdevice_main():
    region_data = {}
    for r in region.query.all():
        region_data[r.regionshort] = r.regionlong

    month_data = count.get_all_month_str()


    return render_template('odata/userdevice_main.html', \
        title='Operational Data', region_data=region_data, month_data=month_data)

@mod_odata.route('/r_m_uddata', methods=['POST', 'GET'])
@login_required
def region_month_userdevice_data():
    result = {}
    load_result_bool = False
    load_result = {}
    info = None
    try:
        month = request.form.get("month", None)
        regionshort = request.form.get("region", None)
        # time = 'March 2015'
        if month is None or regionshort is None:
            raise Exception('Invalid args, month or region cannot be None')

        clock = str_2_clock(month, '%B %Y')
        r = region.query.filter_by(regionshort=regionshort).first()
        if r is None:
            raise Exception(' region input does not exist')
        

        rc_result = {}
        region_counts = r.counts.filter('clock >=' + str(clock)).all()
        for rc in region_counts:
            if rc.clock not in rc_result:
                rc_result[rc.clock] = {}

            rc_result[rc.clock][rc.counttype.counttypename] = rc.value
        


        load_result['data'] = rc_result
        info = 'success'
        load_result_bool = True

    except Exception, e:
        info = str(e)
        print info
        load_result = {}
        load_result_bool = False

    result['load_result'] = load_result
    result['load_result_bool'] = load_result_bool
    result['info'] = info

    return json.dumps(result)
            

monitor/odata/templates/odata/main.html
{% extends "layout.html" %}
{% block body %}
<div class="container marketing">
    <div class="row">
        <div class="col-lg-4">
            <p><a class="btn btn-default" href="{{url_for('odata.mechine_main')}}" role="button">Daily mechine details</a></p>
        </div>
        <div class="col-lg-4">
            <p><a class="btn btn-default" href="{{url_for('odata.userdevice_main')}}" role="button">Daily user device details</a></p>
        </div>
    </div>
</div>
{% endblock %}

monitor/odata/templates/odata/mechine_main.html
{% extends "layout.html" %}
{% block body %}
<script type="text/javascript">
$(document).ready(function () {
    // body...
    var month_data_cache = {};
    // load_or_draw_month_data('June 2015');
    var theaders = {};
    find_headers();
    var time_select_selector = "select.time-select";
    var local_time;
    load_first();

    // $("select.time-select").
    $(document).on('change',time_select_selector,function()
    {
        // console.log($(this).val());
        local_time = $(this).val();
        load_or_draw_month_data(local_time);
    });

    function load_first () {
        // body...
        // console.log($(time_select_selector).val());
        var first_load = $(time_select_selector).val();
        local_time = first_load;
        if (first_load != '') {
            load_or_draw_month_data(first_load);
        };
    }


    function find_headers () {
        $('table.monthdata').find('th').each(function(i,d)
        {
            theaders[$(this).text()] = i;
        });
    }

    function load_or_draw_month_data(month_str){
        if (month_data_cache[month_str] != undefined) {
            draw_month_data(month_data_cache[month_str]);
        }
        else
        {
            load_month_data (month_str)
        }
    }

    function load_month_data (month_str) {
        // body...

        $.getJSON('/odata/monthdata', {month:month_str}, function(data){
            if (data.load_result_bool) {
                month_data_cache[data.load_result['month']] = data.load_result;
                draw_month_data(data.load_result);
            }
            else
            {
                console.log(data.info);
            }
        });

    }


    function draw_month_data (data) {
        // body...
        console.log(data);
        $('table.monthdata > tbody').empty();
        var date_data = data['data'];
        var result_str = '';

        for (var i = 0; i < date_data.length; i++) {
            // date_data[i]
            result_str += '<tr>';
            var td_content = [];
            for (var th in theaders) {
                td_content.push('');
                // console.log(theaders);
            };
            for (var it in date_data[i]["data"])
            {
                td_content[theaders[it]] = date_data[i]["data"][it];
            }
            // console.log(td_content);
            result_str += '<td>' + date_data[i]["date"] + '</td>';
            for (var j = 1; j < td_content.length; j++) {
                result_str += '<td>' + td_content[j] + '</td>';
            };
            result_str += '</tr>';
        };

        $('table.monthdata > tbody').append(result_str);

    }

});
    
    

</script>


<div class="row" style="margin-bottom:20px;">
    <div class="form-horizontal">
        <label class="control-label" style="float:left;">Date:</label>
        <div class="col-sm-5">
            <select class="form-control time-select">
            {% for t in monthes %}
                <option>{{t}}</option>
            {% endfor %}
            </select>
        </div>
    </div>
</div>
<div class="row">
    <table class="table table-default monthdata" style="background-color: #fff;">
        <thead>
            <tr>
                <th>Day</th>
                {% for o in oit %}
                    <th>{{o.displayname}}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

{% endblock %}

monitor/odata/templates/odata/userdevice_main.html
{% extends "layout.html" %}
{% block body %}

<div class="row msg-container" style="margin-bottom:20px; display: none;">
    
</div>

<div class="row" style="margin-bottom:20px;">
    <div class="form-inline">
        <div class="form-group">
            <label for="region-select">Region:</label>
            <select class="form-control" id="region-select">
                {% for rs,rl in region_data.iteritems() %}
                    <option>{{rs}}</option>              
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="month-select">Month:</label>
            <select class="form-control" id="month-select">
                {% for m in month_data %}
                    <option>{{m}}</option>              
                {% endfor %}
            </select>
        </div>
    </div>
</div>




<div class="row user-has-device">
    <div class="panel panel-default">
        <div class="panel-heading">
            Count of user who has specific number of devices.
        </div>
        <table class="table table-striped">
            <thead>
                
            </thead>
            <tbody>
                
            </tbody>
        </table>
    </div>
</div>
<div class="row model">
    <div class="panel panel-default">
        <div class="panel-heading">
            Device count of specific model.
        </div>
        <table class="table table-striped">
            <thead>
                
            </thead>
            <tbody>
                
            </tbody>
        </table>
    </div>
</div>
<div class="row total-count">
    <div class="panel panel-default">
        <div class="panel-heading">
            Total count of this region
        </div>
        <table class="table table-striped">
            <thead>
                <th>Date</th>
                <th>User</th>
                <th>Device</th>
            </thead>
            <tbody>
                
            </tbody>
        </table>
    </div>
</div>



<script type="text/javascript">
    $(document).ready(function(){
        
        var currentRegion = $("#region-select").val();
        var currentMonth = $("#month-select").val();
        var cache = {};

        $("#region-select").change(function(){
            currentRegion = $(this).val();
            updateCurrentData(currentRegion, currentMonth);
        });

        $("#month-select").change(function(){
            currentMonth = $(this).val();
            updateCurrentData(currentRegion, currentMonth);
        });

        updateCurrentData(currentRegion, currentMonth);

        function checkCache(region, month){
            if (cache[region] != undefined) {
                if (cache[region][month] != undefined) {
                    return true;
                };
            };

            return false;
        }

        function updateCurrentData(region, month){
            var isInCache = checkCache(region, month);
            if (isInCache) {
                renderRegionMonthData(cache[region][month]);
            } else {
                var successCallback = function(){
                    renderRegionMonthData(cache[region][month]);
                }

                loadRegionMonthData(region, month, successCallback);
            }
        }

        function loadRegionMonthData(region, month, successCallback){
            
            if (undefined == region || undefined == month) {
                throw "region or month is undefined when load regionMonth data";
            };

            $.ajax({
                url: "/odata/r_m_uddata",
                type: "post",
                data:{"region":region, "month": month},
                dataType: "json",
                success: function (response) {
                    // body..
                    if (response.load_result_bool) {
                        if (cache[region] == undefined) {
                            cache[region] = {};
                        };

                        cache[region][month] = response.load_result;
                        successCallback();
                    };
                },
                error: function (xhr) {
                    // body...
                    console.log(xhr);
                }

            })
        }

        function addMessage(message, type, selector){
            selector = selector || ".msg-container";
            var result_str = '';
            result_str += '<div class="alert alert-' + type + '">';
            result_str += '<button type="button" class="close" data-dismiss="alert">&times;</button>';
            result_str += message;
            result_str += '</div>';
            
            $(selector).append(result_str);
            $(selector).show();
        }

        function removeMessage(selector){
            selector = selector || ".msg-container";
            $(selector).empty();
            $(selector).hide();
        }

        function timestampToStr(UNIX_timestamp){
            var a = new Date(UNIX_timestamp*1000);
            var months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
            var year = a.getFullYear();
            var month = months[a.getMonth()];
            var date = a.getDate();
            var time = date + '/' + month + '/' + year;
            return time;
        }

        function sortNumber(a,b) {
            return a - b;
        }

        function renderRegionMonthData(data){
            var operationalData = data.data;
            if (Object.keys(operationalData).length <= 0) {
                addMessage("Operational data for this region and this month is empty", "danger");
                emptyUserHasDeviceTable();
                emptyModelNumTable();
                emptyTotalNum();
            } else {
                removeMessage();
            }
            
            var modelNumTableHeadArr = [];
            var userHasDeviceNumTableHeadArr = [];
            var displayData = {};
            for(var day in operationalData){
                var dateStr = timestampToStr(day);
                displayData[dateStr] = {};
                var modelNum = {};
                var totalDeviceCount = operationalData[day]["Total device count"];
                var totalUserCount = operationalData[day]["Total user count"];
                var userHasDeviceNumMap = {}
                for (var key in operationalData[day]) {
                    if (key.indexOf("Model") >= 0) {
                        var modelName = key.split(" ")[1];
                        modelNum[modelName] = operationalData[day][key];
                        if (modelNumTableHeadArr.indexOf(modelName) < 0) {
                            modelNumTableHeadArr.push(modelName);
                        };
                    };
                    
                    if (key.indexOf("User has") >= 0) {
                        var num = key.split(" ")[2];
                        userHasDeviceNumMap[num] = operationalData[day][key];
                        if (userHasDeviceNumTableHeadArr.indexOf(num) < 0) {
                            userHasDeviceNumTableHeadArr.push(num);
                        };
                    };
                     
                };
                displayData[dateStr]["modelNum"] = modelNum;
                displayData[dateStr]["userHasDeviceNumMap"] = userHasDeviceNumMap;
                displayData[dateStr]["total"] = {
                    "totalUserCount": totalUserCount,
                    "totalDeviceCount": totalDeviceCount
                }
                // drawUserHasDeviceTable(dateStr, userHasDeviceNumMap);
                // drawModelNumTable(dateStr, modelNum);
                // drawTotalNum(dateStr, totalUserCount, totalDeviceCount);
                // console.log(modelNum, totalDeviceCount, totalUserCount, userHasDeviceNumMap);
            }

            modelNumTableHeadArr.sort();
            userHasDeviceNumTableHeadArr.sort(sortNumber);

            var inputArgs = {
                "modelNumTableHeadArr": modelNumTableHeadArr,
                "userHasDeviceNumTableHeadArr": userHasDeviceNumTableHeadArr,
                "displayData": displayData
            };

            drawData(inputArgs);
        };

        function drawData (inputArgs) {
            emptyUserHasDeviceTable();
            emptyModelNumTable();
            emptyTotalNum();

            var modelNumTableHeadArr = inputArgs["modelNumTableHeadArr"];
            var userHasDeviceNumTableHeadArr = inputArgs["userHasDeviceNumTableHeadArr"];

            var modelNumTableHeadStr = "<tr><th>Date</th>";
            for (var i = 0; i < modelNumTableHeadArr.length; i++) {
                modelNumTableHeadStr += "<th>" + modelNumTableHeadArr[i] + "</th>";
            };
            modelNumTableHeadStr += "</tr>";
            $(".model table > thead").append(modelNumTableHeadStr);


            var userHasDeviceNumTableHeadStr = "<tr><th>Date</th>";
            for (var i = 0; i < userHasDeviceNumTableHeadArr.length; i++) {
                userHasDeviceNumTableHeadStr += "<th>" + userHasDeviceNumTableHeadArr[i] + "</th>";
            };
            userHasDeviceNumTableHeadStr += "</tr>";
            $(".user-has-device table > thead").append(userHasDeviceNumTableHeadStr);

            for (var day in inputArgs["displayData"]) {
                drawUserHasDeviceTable(day, inputArgs["displayData"][day]["userHasDeviceNumMap"], userHasDeviceNumTableHeadArr);
                drawModelNumTable(day, inputArgs["displayData"][day]["modelNum"], modelNumTableHeadArr);
                drawTotalNum(day, inputArgs["displayData"][day]["total"]["totalUserCount"], inputArgs["displayData"][day]["total"]["totalDeviceCount"]);
            }
        };

        function emptyUserHasDeviceTable () {
            $(".user-has-device table > thead").empty();
            $(".user-has-device table > tbody").empty();
        };

        function emptyModelNumTable () {
            $(".model table > thead").empty();
            $(".model table > tbody").empty();
        };

        function emptyTotalNum () {
            $(".total-count table > tbody").empty();
        };

        function drawUserHasDeviceTable (date, data, thead) {

            var tbodyStr = "<tr><td>" + date + "</td>";
            for (var i = 0; i < thead.length; i++) {
                if (data[thead[i]]) {
                    tbodyStr += "<td>" + data[thead[i]] + "</td>";
                } else {
                    tbodyStr += "<td>-</td>";
                }
            };
            tbodyStr += "</tr>";

            $(".user-has-device table > tbody").append(tbodyStr);
        };

        function drawModelNumTable (date, data, thead) {


            var tbodyStr = "<tr><td>" + date + "</td>";
            for (var i = 0; i < thead.length; i++) {
                if (data[thead[i]]) {
                    tbodyStr += "<td>" + data[thead[i]] + "</td>";
                } else {
                    tbodyStr += "<td>-</td>";
                }
            };

            tbodyStr += "</tr>";
            
            $(".model table > tbody").append(tbodyStr);
        };

        function drawTotalNum (date, userCount, deviceCount) {
            
            var countRowStr = "<tr><td>" + date + "</td>";
            countRowStr += "<td>" + userCount + "</td>";
            countRowStr += "<td>" + deviceCount + "</td>";
            countRowStr += "</tr>";
            $(".total-count table > tbody").append(countRowStr);
        };


        

        
    });
</script>

{% endblock %}